// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";
import PageTransition from "@/components/page-transition/PageTransition";
import { AuthProvider } from "@/context/AuthContext";
import { MemberProvider } from "@/context/MemberContext"; // ✅ importe aqui

export const metadata: Metadata = {
  title: "ScoreIt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <MemberProvider>
            <Header />
            {children}
          </MemberProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
