
import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";
import { AuthProvider } from "@/context/AuthContext";
import { MemberProvider } from "@/context/MemberContext";
import { TabProvider } from "@/context/TabContext"; 

export const metadata: Metadata = {
  title: "ScoreIt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <AuthProvider>
          <MemberProvider>
            <TabProvider>
              <Header />
              {children}
            </TabProvider>
          </MemberProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
